### ISSUE TITLE
Nevezzük át a szakot!

### ISSUE THREAD

**Issue by pista26** [battila7/changes#1]
Legyen mondjuk "Elméleti ősrendszertervező informatikus BSc."
Pro:
- nem kell új tanterv
- nem kell új tanári kar
- a hallgatók fordulhatnak tapasztaltabb társaikhoz.

**Comment by elementbound** [comment]
Abszolút tetszik a professzionalizmus. 8/8
U.i.: hol találom a szarkazmus címkét?
